# Generated by Django 3.2.12 on 2022-09-28 14:29

import autoslug.fields
import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('count', models.BigIntegerField()),
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=200, null=True, populate_from='name', unique=True)),
                ('followers', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='profile_image/')),
                ('education', models.CharField(blank=True, max_length=200)),
                ('work', models.CharField(blank=True, max_length=200)),
                ('bio', models.TextField(blank=True)),
                ('skills', models.TextField(blank=True)),
                ('followers_count', models.BigIntegerField(default=0)),
                ('following_count', models.BigIntegerField(default=0)),
                ('post_count', models.BigIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('title', models.CharField(max_length=400)),
                ('body', ckeditor.fields.RichTextField()),
                ('readtime', models.IntegerField()),
                ('coverimage', models.ImageField(blank=True, upload_to='cover_images/')),
                ('active', models.BooleanField(default=True)),
                ('like_count', models.BigIntegerField(default=0)),
                ('save_count', models.BigIntegerField(default=0)),
                ('comment_count', models.BigIntegerField(default=0)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=200, null=True, populate_from='title', unique=True)),
                ('likes', models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL)),
                ('saved', models.ManyToManyField(related_name='saved', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(to='core.Tags')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
