# Generated by Django 3.2.12 on 2022-09-27 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220927_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='coverimage',
            field=models.ImageField(blank=True, upload_to='cover_images'),
        ),
    ]
