# Generated by Django 3.2.12 on 2022-09-27 14:53

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_posts_coverimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=200, null=True, populate_from='title', unique=True),
        ),
        migrations.AddField(
            model_name='tags',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=200, null=True, populate_from='name', unique=True),
        ),
    ]
