# Generated by Django 3.2.12 on 2022-10-03 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20221002_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='follower_count',
            field=models.BigIntegerField(default=0),
        ),
    ]
