# Generated by Django 3.2.12 on 2022-10-03 09:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_tags_follower_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='followers',
            field=models.ManyToManyField(related_name='tagfollower', to=settings.AUTH_USER_MODEL),
        ),
    ]
