# Generated by Django 3.2.12 on 2022-10-03 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_tags_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='draft',
        ),
    ]
