# Generated by Django 3.2.12 on 2022-10-05 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='body',
            field=models.TextField(default=''),
        ),
    ]
