# Generated by Django 3.2.12 on 2022-10-30 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_postreports'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='reply_count',
            field=models.IntegerField(default=0),
        ),
    ]
