# Generated by Django 3.2.12 on 2023-03-18 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_posts_draft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postreports',
            name='description',
        ),
    ]
